apiVersion: v1
kind: deployment
metadata:
  name: my-deploy1
spec:
  replicas: 3
  selector:
    matchlabels:
      app: my-app-cip
  template:
    metadata:
      lables:
        app: my-app-cip
    spec:
      containers:
      - name: my-cont1
        image: nginx:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: service
metadata:
  name: my-svc1
  lables:
    app: my-app-cip
spec:
  type: clusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: my-app-cip
    