apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mycontapp
  template:
    metadata:
      labels:
        app: mycontapp
    spec:
      containers:
      - name: mycontapp-deployment
        image: mycontregwe2.azurecr.io/mycontapp:latest3
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /app/config/secret
      volumes:
       - name: config-volume
         secret:
          secretName: test-sec
---

apiVersion: v1
kind: Service
metadata:
  name: mycontapp-service
spec:
  selector:
    app: mycontapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
