apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mycontapp
  template:
    metadata:
      labels:
        app: mycontapp
    spec:
      containers:
      - name: mycontapp-deployment
        image: mycontregwe2.azurecr.io/mycontapp:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-volume
          mountPath: "/app"
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: mycontapp-service
spec:
  selector:
    app: mycontapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
